version: '3.9'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=5000
      - ASPNETCORE_HTTPS_PORTS=5443
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    depends_on:
      - mariadb
    ports:
      - 8080:80
    links:
      - mariadb
    networks:
      - timetrace
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=${_APP_DB_USER}
      - PMA_PASSWORD=${_APP_DB_PASS}
      - PMA_DB_ENGINE=mariadb
      - PMA_PORT=3306
      - PMA_ARBITRARY=1
    restart: always